server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: gin
  username: root
  password: 123456
  charset: utf8
log:
  level: debug
  filename: test.log
  maxSize: 100
  maxBackups: 2
  maxAge: 2