host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/auth/info:
    get:
      description: 获取用户信息
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":...,"message": "登陆成功"}'
          schema:
            type: string
        "422":
          description: '{"code":422,"message": ...}'
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 用户模块
  /api/v1/auth/login:
    post:
      consumes:
      - multipart/form-data
      description: 用户登陆接口
      parameters:
      - description: 手机号
        in: formData
        name: telephone
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":...,"message": "登陆成功"}'
          schema:
            type: string
        "422":
          description: '{"code":422,"message": ...}'
          schema:
            type: string
      summary: 登陆
      tags:
      - 用户模块
  /api/v1/auth/register:
    post:
      consumes:
      - multipart/form-data
      description: 用户注册接口
      parameters:
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 手机号
        in: formData
        name: telephone
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":...,"message": "注册成功"}'
          schema:
            type: string
        "422":
          description: '{"code":422,"message": ...}'
          schema:
            type: string
      summary: 注册
      tags:
      - 用户模块
swagger: "2.0"
